/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoeq2;

import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samuel
 */
public class FrmReportes extends javax.swing.JFrame {

    /**
     * Creates new form frmProductos
     */
    
    private Productos productos = new Productos();
    public FrmReportes() {
        initComponents();
        iniciarTabla();
    }

    void iniciarTabla() {
        String[] data = new String[5];
        try {
            DefaultTableModel tblModel = (DefaultTableModel) tblVentaGeneral.getModel();
            tblModel.setRowCount(0);
            DataInputStream dataInput = new DataInputStream(new FileInputStream("ventaGeneral.txt"));
            while (dataInput.available() != 0) {
                data[0] = dataInput.readUTF();
                data[1] = dataInput.readUTF();
                data[2] = dataInput.readUTF();
                data[3] = dataInput.readUTF();
                data[4] = dataInput.readUTF();
                tblModel.addRow(data);
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        cmbVendedor = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlBarraInferior = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        pnlVenta = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVentaDetallada = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentaGeneral = new javax.swing.JTable();
        lblDetalle = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");

        pnlFiltros.setPreferredSize(new java.awt.Dimension(250, 329));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Filtrar por:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        cmbVendedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vendedor1", "vendedor2", "admin" }));

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("ID:");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Reportes Productos");

        javax.swing.GroupLayout pnlFiltrosLayout = new javax.swing.GroupLayout(pnlFiltros);
        pnlFiltros.setLayout(pnlFiltrosLayout);
        pnlFiltrosLayout.setHorizontalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblId))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblUsuario))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFiltrosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbVendedor, javax.swing.GroupLayout.Alignment.LEADING, 0, 210, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFiltrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlFiltrosLayout.setVerticalGroup(
            pnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrosLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(pnlFiltros, java.awt.BorderLayout.EAST);

        pnlBarraInferior.setPreferredSize(new java.awt.Dimension(723, 50));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        String fecha = java.time.LocalDate.now().toString();
        String hora = java.time.LocalTime.now().toString();
        lblFecha.setText(fecha + " ; " + hora.substring(0,5));

        javax.swing.GroupLayout pnlBarraInferiorLayout = new javax.swing.GroupLayout(pnlBarraInferior);
        pnlBarraInferior.setLayout(pnlBarraInferiorLayout);
        pnlBarraInferiorLayout.setHorizontalGroup(
            pnlBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraInferiorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        pnlBarraInferiorLayout.setVerticalGroup(
            pnlBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBarraInferior, java.awt.BorderLayout.SOUTH);

        pnlVenta.setLayout(new java.awt.BorderLayout());

        tblVentaDetallada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVentaDetallada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venta", "ID Producto", "Producto", "Cantidad", "Precio", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVentaDetallada);

        tblVentaGeneral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVentaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venta", "Fecha", "Hora", "Usuario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentaGeneralMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVentaGeneral);

        lblDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDetalle.setText("Detalle de Venta");

        lblVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVentas.setText("Ventas");

        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDetalle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lblVentas))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblDetalle)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlVenta.add(jLayeredPane1, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlVenta, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) tblVentaDetallada.getModel();
        String usuario = cmbVendedor.getSelectedItem().toString();
        String idTxt = txtID.getText();

        if (!idTxt.isBlank()) {
            for (int i = 0; i < tblVentaGeneral.getRowCount(); i++) {
                if (idTxt.equals(tblVentaGeneral.getValueAt(i, 0)) && usuario.equals(tblVentaGeneral.getValueAt(i, 3))) {
                    try {
                        DataInputStream dataInputStream = new DataInputStream(new FileInputStream("ventaDetallada.txt"));
                        String id;
                        String idProducto;
                        String producto;
                        String cantidad;
                        String precio;
                        String subtotal;
                        while (dataInputStream.available() != 0) {
                            id = dataInputStream.readUTF();
                            idProducto = dataInputStream.readUTF();
                            producto = dataInputStream.readUTF();
                            cantidad = dataInputStream.readUTF();
                            precio = dataInputStream.readUTF();
                            subtotal = dataInputStream.readUTF();
                            String[] data = {id, idProducto, producto, cantidad, precio, subtotal};
                            if (idTxt.equals(id)) {
                                tblModel.addRow(data);
                            }
                        }
                    } catch (IOException e) {
                        System.out.println(e.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void tblVentaGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentaGeneralMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel) tblVentaDetallada.getModel();
        String idVenta = tblVentaGeneral.getValueAt(tblVentaGeneral.getSelectedRow(), 0).toString();
        tblModel.setRowCount(0);
        try {
            DataInputStream dataInputStream = new DataInputStream(new FileInputStream("ventaDetallada.txt"));
            String id;
            String idProducto;
            String producto;
            String cantidad;
            String precio;
            String subtotal;
            while (dataInputStream.available() != 0) {
                id = dataInputStream.readUTF();
                idProducto = dataInputStream.readUTF();
                producto = dataInputStream.readUTF();
                cantidad = dataInputStream.readUTF();
                precio = dataInputStream.readUTF();
                subtotal = dataInputStream.readUTF();
                String[] data = {id, idProducto, producto, cantidad, precio, subtotal};
                if (idVenta.equals(id)) {
                    tblModel.addRow(data);
                }
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_tblVentaGeneralMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JPanel pnlBarraInferior;
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JPanel pnlVenta;
    private javax.swing.JTable tblVentaDetallada;
    private javax.swing.JTable tblVentaGeneral;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
